# Generated by Django 5.2.4 on 2025-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_counsellor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='firebase_uid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
