# Generated by Django 5.2.4 on 2025-07-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_counsellor_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='firebase_uid',
        ),
    ]
