# Generated by Django 5.2.4 on 2025-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_remove_counsellor_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
