# Generated by Django 5.2.4 on 2025-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_counsellor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='counsellor_photos/'),
        ),
    ]
