# Generated by Django 5.2.4 on 2025-07-18 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_counsellor_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='session_duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='userdetails.counsellor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('session_duration', models.IntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='userdetails.counsellor')),
            ],
        ),
    ]
