# Generated by Django 5.2.4 on 2025-07-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='user',
        ),
    ]
