# Generated by Django 5.2.4 on 2025-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0009_remove_counsellor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='counsellor',
            name='session_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
