# Generated by Django 5.2.4 on 2025-07-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0012_remove_user_user_role_alter_user_firebase_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='counsellor',
        ),
        migrations.RemoveField(
            model_name='callrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='counsellorpayment',
            name='counsellor',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CallRequest',
        ),
        migrations.DeleteModel(
            name='CounsellorPayment',
        ),
    ]
