# Generated by Django 5.2.4 on 2025-08-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0014_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('counsellor', 'Counsellor'), ('admin', 'Admin')], default='normal', max_length=20),
        ),
    ]
