# Generated by Django 5.2.4 on 2025-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0015_user_email_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
