# Generated by Django 5.2.4 on 2025-08-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0016_userprofile_account_holder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_holder_name',
            new_name='razorpay_fund_account_id',
        ),
    ]
