# Generated by Django 5.2.4 on 2025-08-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0017_rename_account_holder_name_userprofile_razorpay_fund_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
