# Generated by Django 5.2.4 on 2025-08-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0018_userprofile_razorpay_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='extra_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('EXTRA_MINUTES_CREDIT', 'Extra Minutes Credit')], max_length=20),
        ),
    ]
