# Generated by Django 5.0.6 on 2025-08-21 12:00

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('userdetails', 'User')
    if not User.objects.filter(phone_number='9874563210').exists():
        User.objects.create_superuser(phone_number='9874563210', password='password123', email='admin@gmail.com')

class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0019_wallet_extra_minutes_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
