# Generated by Django 5.0.6 on 2025-08-21 12:00

from django.db import migrations
from django.contrib.auth.hashers import make_password # Import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('userdetails', 'User')
    if not User.objects.filter(phone_number='9874563210').exists():
        User.objects.create(
            phone_number='9874563210',
            email='admin@gmail.com',
            password=make_password('password123'), # Hash the password
            is_staff=True,
            is_superuser=True,
            is_admin=True # Assuming is_admin is a field on your User model
        )

class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0019_wallet_extra_minutes_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]