# Generated by Django 5.0.6 on 2025-08-21 12:00

from django.db import migrations

def create_admin_userprofile(apps, schema_editor):
    User = apps.get_model('userdetails', 'User')
    UserProfile = apps.get_model('userdetails', 'UserProfile')

    try:
        admin_user = User.objects.get(phone_number='9874563210')

        if not hasattr(admin_user, 'profile') or admin_user.profile is None:
            UserProfile.objects.create(
                user=admin_user,
                user_role='admin',
                phone_number=admin_user.phone_number,
                email=admin_user.email,
            )
        else:
            if admin_user.profile.user_role != 'admin':
                admin_user.profile.user_role = 'admin'
                admin_user.profile.save()

    except User.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0020_createsuperuser'),
    ]

    operations = [
        migrations.RunPython(create_admin_userprofile),
    ]
