# Generated by Django 5.2.4 on 2025-07-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdetails', '0013_remove_callrequest_counsellor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('session_duration', models.IntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='userdetails.userprofile')),
            ],
        ),
    ]
