# Generated by Django 5.2.4 on 2025-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
