# Generated by Django 5.2.4 on 2025-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_callrequest_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
