# Generated by Django 5.2.4 on 2025-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking_razorpay_payment_id_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
