# Generated by Django 5.2.4 on 2025-08-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
