# Generated by Django 5.2.4 on 2025-08-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_payout_razorpay_contact_id_and_more'),
        ('userdetails', '0018_userprofile_razorpay_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this problem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to='userdetails.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(help_text='The problem selected by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_users', to='adminapp.problem')),
                ('user_profile', models.ForeignKey(help_text='The user who selected this problem.', on_delete=django.db.models.deletion.CASCADE, related_name='selected_problems', to='userdetails.userprofile')),
            ],
            options={
                'verbose_name': 'User Problem',
                'verbose_name_plural': 'User Problems',
                'unique_together': {('user_profile', 'problem')},
            },
        ),
    ]
