# Generated by Django 5.2.4 on 2025-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_problem_userproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the problem.', null=True, upload_to='problems/'),
        ),
    ]
